apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapptest3
  name: myapptest3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapptest3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapptest3
    spec:
      containers:
      - image: mitya178/k8sapp:v3
        name: k8sapp
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapptest3
  name: myapptest3
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: myapptest3
  type: NodePort
status:
  loadBalancer: {}
