apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapptest5
  name: myapptest5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapptest5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapptest5
    spec:
      containers:
      - image: mitya178/k8sapp:v5
        name: k8sapp
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapptest5
  name: myapptest5
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: myapptest5
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapptest5-ingress
spec:
  rules:
  - host: example16543231.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapptest5
            port:
              number: 9090
